### ISSUE TITLE
Add a trendline to bar charts

### ISSUE THREAD

**Issue by djaxho** [djaxho/pure-vue-chart#3]
Should add an optional trendline to barcharts

**Comment by L-K-Mist** [comment]
Maybe by doing the line chart we can re-use much of it for trendline?

**Comment by djaxho** [comment]
Yeah for sure 🙂

**Comment by djaxho** [comment]
@L-K-Mist did you want to try it out?

**Comment by L-K-Mist** [comment]
Um, this is my first contribution to an open source project AND the first time working on an npm package, so maybe I should attempt something more minor the first time?  

My vueJs is fairly solid. Found you via that Facebook post btw.

**Comment by djaxho** [comment]
@L-K-Mist no worries. Once i work on it a bit more I'll try to make a lot more basic issues so it's a little easier to jump in to :)

**Comment by Rechousa** [comment]
Please check the pull request #10
