### ISSUE TITLE
Add option to allow custom templates for labels

### ISSUE THREAD

**Issue by lafriks** [djaxho/pure-vue-chart#8]
For example using slots to allow more customization

**Comment by talieScript** [comment]
Hi, 
I would like to do this if you don't mind? But just to clarify, where would the labels be going?
do you mean replacing the x&y axis labels?

**Comment by talieScript** [comment]
Also how about adding an optional percentage/value label hovering above the bar or inside it? It could also smoothly count up or down as the values changed.
Example:
https://www.statisticshowto.datasciencecentral.com/wp-content/uploads/2013/01/bar_chart_big.jpg

**Comment by lafriks** [comment]
I meant for label below bar

**Comment by talieScript** [comment]
Check out https://github.com/djaxho/pure-vue-chart/pull/12

I think this could be improved with some dynamic classes on the label text elements, then someone could add their own CSS too.
